name: storjshare
version: git
summary: farm data on the Storj network.
description: |
  Earn money by sharing your hard drive space.
  Daemon + CLI for farming data on the Storj network.

grade: stable
confinement: strict

apps:
  storjshare:
    command: bin/storjshare
    plugs: [network, network-bind, home]

parts:
  storjshare-daemon:
    source-subdir: ..
    plugin: nodejs
    node-engine: '6.11.3'
    install: npm install
    build-packages: [git, python, build-essential]
    stage-packages: [nano]
